### PR TITLE
Update James' status to Former Editor

### PR DESCRIPTION
**Pull request by anssiko**
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webmachinelearning-ethics/pull/29.html" title="Last updated on Aug 9, 2023, 1:15 PM UTC (77d8371)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webmachinelearning-ethics/29/2d4ec65...77d8371.html" title="Last updated on Aug 9, 2023, 1:15 PM UTC (77d8371)">Diff</a>

### CODE REVIEW

**Review by bbcjamesfletcher — APPROVED** [review]

**Comment by anssiko** [comment]
@bbcjamesfletcher, thanks for your significant contributions to this effort on behalf of the WG!

**Comment by anssiko** [comment]
@dontcallmedom the CI build failed https://github.com/webmachinelearning/webmachinelearning-ethics/actions/runs/5810048750/job/15750148458#step:19:1512

The error message (`node -e 'require("@actions/core").setFailed("Failed. See details above.")'`) was not helping me forward at this time. Can you check if there's an obvious fix?

**Comment by anssiko** [comment]
@dontcallmedom I re-run the failed job https://github.com/webmachinelearning/webmachinelearning-ethics/actions/runs/5810048750 and got the following message:

>The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

I noticed you updated the workflow to use checkout@v3 in https://github.com/webmachinelearning/webmachinelearning-ethics/commit/28ee7585e063029d984c61d54b80fc9cacbae2b3 which supposedly fixed this and on the next push to main TR is again in sync?

Thanks for your help with this!

**Comment by dontcallmedom** [comment]
indeed, I fixed the workflow; there is now a pubrules fix that is needed:
> The document must mention the governing process: 12 June 2023

I'll look into this next

**Comment by dontcallmedom** [comment]
with the process link fix, it went through https://www.w3.org/TR/2023/DNOTE-webmachinelearning-ethics-20230811/

**Comment by anssiko** [comment]
@dontcallmedom thanks for debugging and fixing this!

**Pull request merged**
