### PR TITLE
Expand transparency and explainability mitigations

### PR DESCRIPTION
**Pull request by anssiko**
- Link to WebSHAP as another example <https://poloclub.github.io/webshap/>

***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webmachinelearning-ethics/pull/32.html" title="Last updated on Jan 8, 2024, 7:42 AM UTC (4c1b44d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webmachinelearning-ethics/32/7b10ab3...4c1b44d.html" title="Last updated on Jan 8, 2024, 7:42 AM UTC (4c1b44d)">Diff</a>

### CODE REVIEW

**Comment by anssiko** [comment]
(Please note [WebSHAP](https://poloclub.github.io/webshap/) already links to this Ethical Principles document. Here we create a backlink.)

**Review by dontcallmedom — APPROVED** [review]

**Comment by anssiko** [comment]
@dontcallmedom CI deploy failed https://github.com/webmachinelearning/webmachinelearning-ethics/actions/runs/7445084552/job/20252666527, can you look into this? Builds clean AFAICT. Thanks!

**Comment by dontcallmedom** [comment]
fixed, see https://www.w3.org/TR/2024/DNOTE-webmachinelearning-ethics-20240108/

**Comment by anssiko** [comment]
Much thanks! Is https://www.w3.org/pubrules/ still the best tool to test for TR compliance?

Note to self: Roll up a CLI command to that takes a .bs file as an argument to test against the Specberus REST API. Unless someone has made that already.

**Comment by dontcallmedom** [comment]
At least in this case, the deploy failure wasn't linked to pubrules per se and had been detected by the CI at the Pull Request level https://github.com/webmachinelearning/webmachinelearning-ethics/actions/runs/7444503961/job/20251010838

That being said, it looks like [spec-prod](https://github.com/w3c/spec-prod) can be [configured to do more pubrules checking](https://github.com/w3c/spec-prod/pull/100) pre-deployment if you want to make sure more errors get caught.

**Pull request merged**
