### PR TITLE
Add Transparency and explainability Risk TE-R1

### LINKED ISSUE #25: It is unclear what the Risk TE-R1 is
Under section 6.6, [Risk TE-R1](https://www.w3.org/TR/webmachinelearning-ethics/#te-r1) is currently  "Issue 4: Identify risk mapping for corresponding mitigation". Does it mean this section is work-in-progress?

Thanks!

### PR DESCRIPTION
**Pull request by anssiko**
Fix #25

***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webmachinelearning-ethics/pull/26.html" title="Last updated on Nov 25, 2022, 12:53 PM UTC (11883f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webmachinelearning-ethics/26/5717f64...11883f7.html" title="Last updated on Nov 25, 2022, 12:53 PM UTC (11883f7)">Diff</a>

### CODE REVIEW

**Review by dontcallmedom — APPROVED** [review]

**Comment by anssiko** [comment]
Thanks @dontcallmedom!

**Comment by anssiko** [comment]
@dontcallmedom [auto-publish.yml in main](https://github.com/webmachinelearning/webmachinelearning-ethics/blob/main/.github/workflows/auto-publish.yml) did not publish to https://www.w3.org/TR/webmachinelearning-ethics/

OTOH, the other [auto-publish.yml in gh-pages](https://github.com/webmachinelearning/webmachinelearning-ethics/blob/gh-pages/.github/workflows/auto-publish.yml) did deploy the ED succesfully: https://webmachinelearning.github.io/webmachinelearning-ethics/

Can you see what the issue is and how to fix it?

**Comment by dontcallmedom** [comment]
done https://www.w3.org/TR/2022/DNOTE-webmachinelearning-ethics-20221125/ - the repo was missing the echidna key needed for auto-deploy

**Comment by anssiko** [comment]
Thanks!

**Pull request merged**
